export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  FETCH_AVAILABLE_SLOTS_START: "cart/FETCH_AVAILABLE_SLOTS_START",
  FETCH_AVAILABLE_SLOTS_SUCCESS: "cart/FETCH_AVAILABLE_SLOTS_SUCCESS",
  FETCH_AVAILABLE_SLOTS_FAILURE: "cart/FETCH_AVAILABLE_SLOTS_FAILURE",
};
